import stdio
import sys
from markov_model import MarkovModel


# Takes two integers k and T as command-line arguments, reads the input text
# from standard input and builds a Markov model of order k from the input
# text; then, starting with the k-gram consisting of the first k characters
# of the input text, prints out T characters generated by simulating a
# trajectory through the corresponding Markov chain.
def main():
    k, T = int(sys.argv[1]), int(sys.argv[2])
    text = sys.stdin.read()
    kgram = text[:k]
    model = MarkovModel(text, k)
    model.MarkovModel.gen(kgram, T)


if __name__ == '__main__':
    main()
